/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Tue Apr  7 19:49:05 2015
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include "mavlink_msg_gen.h"
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void mavlink_msg_gen_sfuntion_Outputs_wrapper(const real_T *time_usecs,
                          const real_T *accel,
                          const real_T *gyro,
                          const real_T *mag,
                          const real_T *euler,
                          const real_T *quat,
                          const real_T *abs_pressure,
                          const real_T *diff_pressure,
                          const real_T *temperature,
                          const real_T *v_body,
                          const real_T *lla,
                          const uint8_T *fix_type,
                          const real_T *gnd_vel,
                          const real_T *v_ned,
                          const real_T *cog,
                          const uint8_T *target_sys_id,
                          const uint8_T *msg_id,
                          real_T *y)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/
int i=0;real_T phi_dot,theta_dot,psi_dot;uint16_T ind_airspeed,true_airspeed;
// const uint16_t out_msg_size=MavlinkMessageSizes[(uint8_t)msg_id[0]]+MAVLINK_NUM_NON_PAYLOAD_BYTES;
static uint8_T out_msg[MAVLINK_MAX_PACKET_LEN]={0};
    real_T alpha = atan(v_body[2]/v_body[0]);
    real_T wind_mag = sqrt(v_body[0]*v_body[0] + v_body[1]*v_body[1] + v_body[2]*v_body[2]);
    real_T beta = asin(v_body[1]/wind_mag);
    int32_T lat_int = (int32_T)lla[0]*1000000;
    int32_T lon_int = (int32_T)lla[1]*1000000;
    int32_T alt_int = (int32_T)lla[3]*1000000;
    real_T rho0 = 1013.25;
    //http://www.srh.noaa.gov/images/epz/wxcalc/pressureAltitude.pdf
    real_T pressure_alt = (1-pow((abs_pressure[0]/rho0),0.190284))*145366.45*0.3048;
          
    switch(msg_id[0]){
        case MAVLINK_MSG_ID_HEARTBEAT: //mavlink_msg_heartbeat_pack(mavlink_system.sysid,MAV_COMP_ID_SYSTEM_CONTROL,&out_msg_ml, MAV_TYPE_FIXED_WING, MAV_AUTOPILOT_GENERIC, MAV_MODE_AUTO_ARMED, MAV_MODE_FLAG_MANUAL_INPUT_ENABLED, MAV_STATE_ACTIVE);
            mavlink_msg_heartbeat_pack(mavlink_system.sysid, mavlink_system.compid,&out_msg_ml,mavlink_system.type, mavlink_system.autopilot, mavlink_system.mode,mavlink_system.custom_mode, mavlink_system.state);
            break;
        //Need to get the sys_id of the target system from mavlink. Current need to give it as an input
        case MAVLINK_MSG_ID_COMMAND_LONG:mavlink_msg_command_long_pack(mavlink_system.sysid, mavlink_system.compid, &out_msg_ml, target_sys_id[0], MAV_COMP_ID_ALL, MAV_CMD_DO_SET_MODE, 4, MAV_MODE_FLAG_AUTO_ENABLED | MAV_MODE_FLAG_SAFETY_ARMED | MAV_MODE_FLAG_HIL_ENABLED, 0, 0, 0, 0, 0, 0);
            break;//msg_id:76
        case MAVLINK_MSG_ID_HIL_SENSOR:            
            mavlink_msg_hil_sensor_pack(mavlink_system.sysid, mavlink_system.compid, &out_msg_ml,time_usecs[0], accel[0], accel[1], accel[2], gyro[0], gyro[1], gyro[2], mag[0], mag[1], mag[2], abs_pressure[0], diff_pressure[0], pressure_alt, temperature[0], 4095);
            break; //msg_id:107
        case MAVLINK_MSG_ID_HIL_GPS: 
             mavlink_msg_hil_gps_pack(mavlink_system.sysid, mavlink_system.compid, &out_msg_ml,time_usecs[0], fix_type[0], lat_int, lon_int, alt_int, 65535, 65535, (uint16_T) gnd_vel[0]*100, (int16_T) v_ned[0]*100, (int16_T) v_ned[1]*100, (int16_T) v_ned[2]*100, (uint16_T) cog[0]*100, 255);
            break;  //msg_id:113
        case MAVLINK_MSG_ID_HIL_STATE_QUATERNION: 
//             http://www.princeton.edu/~stengel/MAE331Lecture9.pdf
//             real_T phi_dot = p + (sin(phi)*tan(theta)*q) + (cos(phi)*tan(theta)*r);
//             real_T theta_dot = cos(phi)*q + (-sin(phi)*r);
//             real_T psi_dot = ((sin(phi)/cos(theta))*q) + ((cos(phi)/cos(theta))*r);     
            
            phi_dot = gyro[0];
            theta_dot = gyro[1];
            psi_dot = gyro[2];       
            
            ind_airspeed = (uint16_T) sqrt((2*diff_pressure[0])/rho0)*100;
            true_airspeed = (uint16_T) sqrt((2*diff_pressure[0])/abs_pressure[0])*100;
            //float Quat[4]={q1,q2,q3,q4};
            mavlink_msg_hil_state_quaternion_pack(mavlink_system.sysid, mavlink_system.compid, &out_msg_ml,time_usecs, quat, phi_dot, theta_dot, psi_dot, lat_int, lon_int, alt_int, (int16_t) v_body[0]*100, (int16_t) v_body[1]*100, (int16_t) v_body[2]*100, ind_airspeed, true_airspeed, (int16_t) accel[0]*100, (int16_t) accel[1]*100, (int16_t) accel[2]*100);
            break; //msg_id:115
    }
    mavlink_msg_to_send_buffer(out_msg,&out_msg_ml);
    for(i=0;i<MavlinkMessageSizes[(uint16_T)msg_id]+MAVLINK_NUM_NON_PAYLOAD_BYTES;i++){  y[i]=out_msg[i]; }
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
